---
abstract: 'install generated debian package'
author:
  - 'Vyacheslav Matyukhin <mmcleric@yandex-team.ru>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Deb
no_index:
  directory:
    - xt/packages
requires:
  Dist::Zilla::App: 0
  Dist::Zilla::Role::BeforeBuild: 0
  IPC::System::Simple: 0
  Moose: 0
  autodie: 0
  strict: 0
  warnings: 0
version: 0.04
