---
abstract: 'run debc on generated debian package'
author:
  - 'Vyacheslav Matyukhin <mmcleric@yandex-team.ru>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101591'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Deb
requires:
  Dist::Zilla::App: 0
  IPC::System::Simple: 0
  autodie: 0
resources:
  homepage: http://github.com/berekuk/Dist-Zilla-Deb/tree
  repository: git://github.com/berekuk/Dist-Zilla-Deb.git
version: 0.01
