---
abstract: 'run debc on generated debian package'
author:
  - 'Vyacheslav Matyukhin <mmcleric@yandex-team.ru>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Deb
no_index:
  directory:
    - xt/packages
requires:
  Dist::Zilla::App: 0
  Dist::Zilla::Role::BeforeBuild: 0
  IPC::System::Simple: 0
  Moose: 0
  autodie: 0
resources:
  homepage: git://github.com/berekuk/Dist-Zilla-Deb/tree
  repository: git://github.com/berekuk/Dist-Zilla-Deb.git
version: 0.03
