---
abstract: XXX
author:
  - 'Vyacheslav Matyukhin <mmcleric@yandex-team.ru>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101591'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: X
version: 0.01
